/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#795354",
        "secondary-fixed-dim": "#ecbbba",
        "surface-dim": "#dcd9dd",
        "surface-container-high": "#eae7eb",
        "background": "#fbf8fc",
        "on-secondary-fixed-variant": "#603d3e",
        "outline-variant": "#c3c8c0",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdad9",
        "on-tertiary-fixed-variant": "#5d3e44",
        "surface-bright": "#fbf8fc",
        "surface-container-highest": "#e4e1e5",
        "surface-container": "#f0edf1",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#2f1314",
        "on-primary-fixed-variant": "#374c3b",
        "tertiary-fixed-dim": "#e7bcc3",
        "inverse-surface": "#303033",
        "error-container": "#ffdad6",
        "surface-tint": "#4e6451",
        "on-surface": "#1b1b1e",
        "on-primary": "#ffffff",
        "tertiary": "#77555c",
        "primary-container": "#8fa691",
        "on-primary-container": "#273c2b",
        "primary-fixed": "#d1e9d2",
        "surface": "#fbf8fc",
        "surface-variant": "#e4e1e5",
        "inverse-primary": "#b5cdb6",
        "secondary": "#7b5455",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b5cdb6",
        "secondary-container": "#fdcbcb",
        "tertiary-container": "#be969d",
        "surface-container-lowest": "#ffffff",
        "outline": "#737872",
        "on-error-container": "#93000a",
        "primary": "#4e6451",
        "on-background": "#1b1b1e",
        "on-surface-variant": "#434842",
        "tertiary-fixed": "#ffd9df",
        "on-tertiary-container": "#4c2f35",
        "inverse-on-surface": "#f3f0f4",
        "on-tertiary-fixed": "#2d141a",
        "on-primary-fixed": "#0c2011",
        "surface-container-low": "#f5f3f6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem"
      },
      "spacing": {
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "margin-desktop": "2.5rem",
        "container-max": "1280px",
        "section-gap": "5rem"
      },
      "fontFamily": {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
